export const reasons: string[] = [
  "TODO: alasan 1 — sekalimat kenapa kamu",
  "TODO: alasan 2 — sekalimat kenapa kamu",
  "TODO: alasan 3 — sekalimat kenapa kamu",
  "TODO: alasan 4 — sekalimat kenapa kamu",
  "TODO: alasan 5 — sekalimat kenapa kamu",
  "TODO: alasan 6 — sekalimat kenapa kamu",
  "TODO: alasan 7 — sekalimat kenapa kamu",
  "TODO: alasan 8 — sekalimat kenapa kamu",
  "TODO: alasan 9 — sekalimat kenapa kamu",
  "TODO: alasan 10 — sekalimat kenapa kamu",
  "TODO: alasan 11 — sekalimat kenapa kamu",
  "TODO: alasan 12 — sekalimat kenapa kamu",
  "TODO: alasan 13 — sekalimat kenapa kamu",
  "TODO: alasan 14 — sekalimat kenapa kamu",
  "TODO: alasan 15 — sekalimat kenapa kamu",
  "TODO: alasan 16 — sekalimat kenapa kamu",
  "TODO: alasan 17 — sekalimat kenapa kamu",
  "TODO: alasan 18 — sekalimat kenapa kamu",
  "TODO: alasan 19 — sekalimat kenapa kamu",
  "TODO: alasan 20 — sekalimat kenapa kamu",
];