export const reasons: string[] = [
  "Karena senyummu bisa mengubah hari yang berat jadi ringan.",
  "Karena kamu mendengarkan dengan sungguh-sungguh, bukan sekadar menunggu giliran bicara.",
  "Karena tawamu menular, dan aku selalu ikut tertawa tanpa tahu alasannya.",
  "Karena kamu peduli pada hal-hal kecil yang sering orang lain lewatkan.",
  "Karena di dekatmu aku merasa boleh menjadi diriku sendiri.",
  "Karena kamu berani bermimpi besar, dan itu menular padaku.",
  "Karena caramu menyayangi orang-orang di sekitarmu terasa tulus.",
  "Karena kamu sabar, bahkan di hari-hari yang tidak mudah.",
  "Karena suaramu adalah salah satu yang paling menenangkan yang kukenal.",
  "Karena kamu selalu tahu cara membuat suasana jadi hangat.",
  "Karena kamu tetap baik hati meski dunia kadang tidak ramah.",
  "Karena bersamamu, hal sederhana pun terasa seperti petualangan.",
  "Karena kamu tidak pernah berhenti belajar dan bertumbuh.",
  "Karena caramu menatap sesuatu yang kamu sukai selalu terlihat indah.",
  "Karena kamu membuatku ingin menjadi versi diriku yang lebih baik.",
  "Karena kamu bisa menemukan sisi lucu dari hampir apa saja.",
  "Karena kehadiranmu terasa seperti rumah.",
  "Karena kamu kuat, dan sekaligus tidak malu untuk lembut.",
  "Karena setiap cerita bersamamu layak untuk diingat.",
  "Karena kamu adalah kamu, dan itu sudah lebih dari cukup.",
];
